name: dragonsapprentice
adopt-info: dragonsapprentice-source
base: core22
architectures:
- amd64
confinement: strict
grade: stable
issues: https://github.com/kenvandine/dragonsapprentice-snap/issues
contact: https://github.com/kenvandine/dragonsapprentice-snap/issues

apps:
  dragonsapprentice:
    desktop: com.endlessnetwork.dragonsapprentice.desktop
    extensions: [gnome]
    command: DragonsApprentice/DragonsApprentice.x64
    plugs:
      - audio-playback
      - joystick
      - network

parts:
  dragonsapprentice:
    source: https://github.com/endless-network/DragonsApprentice_Binary/releases/download/v1.1/DragonsApprentice.zip
    plugin: dump
    override-prime: |
      craftctl default
      chmod +x $CRAFT_PRIME/DragonsApprentice/DragonsApprentice.x64
  dragonsapprentice-source:
    source: https://github.com/endless-network/DragonsApprentice_Binary/archive/refs/tags/v1.1.tar.gz
    plugin: dump
    parse-info: [com.endlessnetwork.dragonsapprentice.appdata.xml]
    override-pull: |
      craftctl default
      sed -i 's|Icon=com.endlessnetwork.dragonsapprentice$|Icon=${SNAP}/meta/gui/icon.png|g' $CRAFT_PART_SRC/com.endlessnetwork.dragonsapprentice.desktop
      sed -i 's|Exec=com.endlessnetwork.dragonsapprentice.sh$|Exec=dragonsapprentice|g' $CRAFT_PART_SRC/com.endlessnetwork.dragonsapprentice.desktop
      # Work around the latest version number missing from the releases section of appdata
      sed -i 's|version="1.0|version="1.1|g' $CRAFT_PART_SRC/com.endlessnetwork.dragonsapprentice.appdata.xml

      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp com.endless_network.dragonsapprentice128.png $CRAFT_PART_INSTALL/meta/gui/icon.png
